# My Notes in Python

In [2]:
import cmath as cm # τρόπος κλήσης πακέτου (μαθηματικών εξισώσεων)
dir(cm) # Εμφάνιση περιεχομάνων αντικειμένου

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atanh',
 'cos',
 'cosh',
 'e',
 'exp',
 'inf',
 'infj',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'log',
 'log10',
 'nan',
 'nanj',
 'phase',
 'pi',
 'polar',
 'rect',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau']

### Τελεστές

In [16]:
print(2+3) # Addition '+'
print(3-2) # Subtraction '-'
print(2*3) # Multiplication '*'
print(3/2) # Division '/'
print(7//3) # Integer (floor) division '//'
print(7%3) # Modulus (remainder division) '%'
print(2**3) # Exponent '**'
1==2 or 3<5 and 1!=7 or 8>=4 # Comparison operators: ==, <, >, >=, <=, != (not equal), <> (not equal)

5
1
6
1.5
2
1
8


True

### Τύποι μεταβλητών

In [10]:
a1 = 'name'
type(a1) # Επιστρέφει τον τύπο της μεταβλητής

str

In [11]:
a2 = 8
type(a2)

int

In [12]:
a3 = 8.2
type(a3) # μπορεί ο τύπος να είναι και συνάρτηση - function

float

### Μεταβλητές Tuple

In [13]:
# tuple - δεν μπορεί να αλλάξει τα στοιχεία του από την στιγμή που θα δημιουργηθεί
x = (1,2,'c',4.1)
type(x)

tuple

### Μεταβλητές List

In [19]:
# list - μπορεί να αλλάξει το μήκος, το πλήθος και οι τιμές των στοιχείων 
x = [1,2,'c',4.1]
type(x)

list

In [20]:
x.append('e')
print(x)

[1, 2, 'c', 4.1, 'e']


### Loops For, while

In [4]:
for item in x:
    print(item)

1
2
c
4.1
e


In [5]:
i=0
while (i!=len(x)):
    print(x[i])
    i=i+1

1
2
c
4.1
e


### Παράδειγμα if then else

In [34]:
var = 100
if var == 200:
   print("1 - Got a true expression value")
   print(var)
elif var == 150:
   print("2 - Got a true expression value")
   print(var)
elif var == 100:
   print("3 - Got a true expression value")
   print(var)
else:
   print("4 - Got a false expression value")
   print(var)

3 - Got a true expression value
100


### Πράξεις με λίστες και δυανίσματα 

In [7]:
print((1,2,3)+(4,5))
print((1,2,3)*2)
print(2 in (1,2,3))

(1, 2, 3, 4, 5)
(1, 2, 3, 1, 2, 3)
True


In [21]:
print(x[3]) # Επιστρέφει την τιμή του στοιχείου στη θέση 3. Η αρίθμηση ξεκινά από το 0
print(x[-3]) # Επιστρέφει την τιμή του στοιχείου στη θέση 3 από το τέλος.
print(x[1:3]) # Επιστρέφει τα στοιχεία από την θέση 1 έως την θέση 3 (όχι την 3)

4.1
c
[2, 'c']
am
nam
ame


In [ ]:
x='name'
print(x[1:3]) # ισχύει και σε string
print(x[:3])
print(x[1:])

### Πράξεις με String

In [23]:
Sn = 'Surname'
Fn = 'Firstname'
print(Sn + ' ' + Fn)
print(Fn * 3)
print('name' in Sn)
print('Name' in Sn)

Surname Firstname
FirstnameFirstnameFirstname
True
False
My


In [ ]:
t = 'My name is Fisrt Name Last Name'
print(t.split(' ')[0]) # διαχωρίζει ένα string με τον διαχωριστή που δηλώσαμε και το κάνει list

In [ ]:
'name' + str(100)

In [28]:
x = (1,2,3)
a,b,c = x # πρέπει όσα είναι τα στοιχεία του διανύσματος να είναι και οι μεταβλητές
print(a)
print(b)
print(c)

1
2
3


### Μεταβλητές Dictionary (dict) 

In [24]:
# Dictionary (dict) μπορούμε να έχουμε labels 
x = {'BMW' : 'M3', 'Toyota':'Prius', 'Honda': 'Civic'}
x['Toyota']

'Prius'

In [26]:
for car in x:
    print(x[car])
    
print(' ')

for model in x.values():
    print(model)
    
print(' ')

for car, model in x.items():
    print(car + ' - ' + model)

M3
Prius
Civic
 
M3
Prius
Civic
 
BMW - M3
Toyota - Prius
Honda - Civic


In [29]:
# Food for thought
sales_record = {'price':2.6, 'num_items':4,'person':'Mitsos'}
sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Mitsos bought 4 item(s) at a price of 2.6 each for a total of 10.4


### Δημιουργία (declare) functions

In [35]:
def addnums(x,y):
    return x+y
# Call functions
addnums(1,2)

def addnums2(x,y, z=None):
    if (z==None):
        return x+y
    else :
        return x+y+z
# Call functions
addnums2(1,2)
addnums2(1,2,3)

6

In [31]:
import csv

%precision 2  # Ορίζονται δύο δεκαδικά ψηφία για τα float

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3]

[OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '307'),
              ('horsepower', '130'),
              ('weight', '3504'),
              ('acceleration', '12'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'chevrolet chevelle malibu')]),
 OrderedDict([('mpg', '15'),
              ('cylinders', '8'),
              ('displacement', '350'),
              ('horsepower', '165'),
              ('weight', '3693'),
              ('acceleration', '11.5'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'buick skylark 320')]),
 OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '318'),
              ('horsepower', '150'),
              ('weight', '3436'),
              ('acceleration', '11'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'plymouth satellite')])]

In [33]:
len(mpg)

398

In [34]:
mpg[0].keys()

odict_keys(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'])

In [38]:
sum(float(d['weight']) for d in mpg)/len(mpg)

2970.42

In [39]:
# Κατηγοριοποίηση ανά Κυλίνδρους
cyl = set(d['cylinders'] for d in mpg)
cyl

{'3', '4', '5', '6', '8'}

In [40]:
wgtMpgbyCyl = []  # Δημιουργία κενής λίστας

for c in cyl:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cylinders'] == c:
            summpg += float(d['weight'])
            cyltypecount += 1
    wgtMpgbyCyl.append((c,summpg/cyltypecount))    

wgtMpgbyCyl.sort(key=lambda x: x[0])  # lambda is covered in advance python lambda and list comperhension
wgtMpgbyCyl

[('3', 2398.50),
 ('4', 2308.13),
 ('5', 3103.33),
 ('6', 3198.23),
 ('8', 4114.72)]

## Διαχείρσηση ημερομηνιών

In [38]:
import datetime as dt # πακέτο ημερομηνιών
import time as tm # πακέτο ώρας

In [39]:
myDate = dt.datetime.now() # Ημερομηνία και ώρα την στιγμή που τρέχει η εντολή

In [40]:
print(myDate)
print(myDate.year)
print ("Current date and time using instance attributes:")
print ("Current year: %d" % myDate.year)
print ("Current month: %d" % myDate.month)
print ("Current day: %d" % myDate.day)
print ("Current hour: %d" % myDate.hour)
print ("Current minute: %d" % myDate.minute)
print ("Current second: %d" % myDate.second)
print ("Current microsecond: %d" % myDate.microsecond)

2017-08-20 17:52:31.146864
2017
Current date and time using instance attributes:
Current year: 2017
Current month: 8
Current day: 20
Current hour: 17
Current minute: 52
Current second: 31
Current microsecond: 146864


In [11]:
myDate = dt.datetime.fromtimestamp(tm.time())  # Ημερομηνία και ώρα την στιγμή που τρέχει η εντολή
print(myDate)
myDate = dt.date(2008, 1, 20) # Ανάθεση τιμής ημερομηνίας σε μεταβλητή
print(myDate)
myDate = dt.date.today() # Ανάθεση τιμής σημερινής ημερομηνίας σε μεταβλητή
print(myDate)

2017-08-19 17:21:40.661582
2008-01-20
2017-08-19


### Πράξεις με ημερομηνίες

In [20]:
DeltaDays = dt.timedelta(days=10) # Διάστημα ημερών
print(myDate - DeltaDays) # Πίσω κατά DeltaDays μέρες
print(myDate + DeltaDays) # Μπροστά κατά DeltaDays μέρες

DeltaWeeks = dt.timedelta(weeks=1)
print(myDate - DeltaWeeks) # Πίσω κατά DeltaDays εβδομάδες πίσω, από Δευτέρα σε Δευτέρα

# Επίσης έχουμε
today = dt.date.today()
someday = dt.date(2008, 12, 25)
diff = today - someday
print(diff) # Ακριβείς μεταβολή σε ώρες λεπτά κλπ
print(diff.days) # Μεταβολή σε μέρες

2017-08-09
2017-08-29
2017-08-12
3159 days, 0:00:00
3159


In [24]:
# Παραδείγματα Κώδικα με πράξεις σε ημερονημίες

D1 = dt.date.today()

D2 = D1 + dt.timedelta(days=1) # Next Day
D2 = D1 + dt.timedelta(days=-1) # Previous Day

D2 = dt.date(D1.year, D1.month, 1)	# Πρώτη μέρα του μήνα
D2 = dt.date(D1.year, D1.month+1, 1) + dt.timedelta(days=-1) # Τελευταία μέρα του μήνα

# x Μήνες πίσω
xMonths = 2
difM = D1.month - xMonths

if D1.month == 2 and D1.day == 29 :
   D1 = D1 + dt.timedelta(days=-1)
else:
   D1 = D1
 
if difM > 0:
   D2 = dt.date(D1.year, D1.month-xMonths, D1.day)
else:
   D2 = dt.date(D1.year-1, 12 - difM*(-1), D1.day)
print(D2)

# x Μήνες μπροστά
xMonths = 2
D1 = dt.date(2008, 3, 20)
#D1 = datetime.date.today()
difM = D1.month + xMonths
dt.date(D1.year, D1.month + xMonths, D1.day)

2017-06-19


datetime.date(2008, 5, 20)

## Objects

In [25]:
class Person:
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [26]:
person = Person()
person.set_name('Firstname Lastname')
person.set_location('City, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name,person.location,person.department))    

Firstname Lastname live in City, MI, USA and works in the department School of Information


## Map() function

In [10]:
store1 = [10.00,11.00,12.34,2.34]
store2 = [9.00,11.10,12.34,2.01]
cheapest = map(min,store1,store2)
print(cheapest)

for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


## Lambda Syntax

In [11]:
my_function = lambda a, b, c : a + b
my_function(1,2,3)

3

In [12]:
# example
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))
#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [13]:
# Lists με lambdas
myList = []
for number in range(0,1000):
    if number % 2 == 0:
        myList.append(number)
print(myList)
# είναι το ίδιο με το επόμενο
myList = [number for number in range(0,1000) if number % 2 == 0]
print(myList)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

In [15]:
# Παράδειγμα 1o
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

In [16]:
# Παράδειγμα 2o
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:50] # Display first 50 ids

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

## Numpy πακέτο

In [3]:
import numpy as np # Numpy πακέτο

In [34]:
# Creating Arrays
myList = [1,2,3]
x = np.array(myList)
print(x)
y = np.array([4,5,6])
print(y)
n = np.array([(7,8,9),(10,11,12)]) # Δημιουργία πίνακα δύο διαστάσεων
print(n)

[1 2 3]
[4 5 6]
[[ 7  8  9]
 [10 11 12]]


In [31]:
n.shape # Επιστρέφει τις διαστάσεις του πίνακα γραμμές/στήλες

(2, 3)

In [5]:
ar = np.arange(0,30,2) # Δημιουργία πίνακα από τον αριθμό 0 έως το 30 με βήμα 2
print(ar)
lin = np.linspace(0,4,9) # Δημιουργία πίνακα 9 θέσεων από τον αριθμό 0 έως το 4 και ισόποσες αποστάσεις
print(lin)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4. ]


### Πράξεις με arrays

In [6]:
x = np.ones([3,2]) # Δημιουργία πίνακα με τιμές ίσο 1
print(x)
x = np.zeros([3,2]) # Δημιουργία πίνακα με τιμές ίσο 0
print(x)
x = np.eye(4) # Δημιουργία πίνακα 4x4 με διαγώνιο 1 και τις υπόλοιπες 0
print(x)
x = np.diag(ar) # Δημιουργία πίνακα με διαγώνιο τις τιμές του δυανίσματος και τις υπόλοιπες 0
print(x)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 12  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 16  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 18  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 22  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]]


In [8]:
x = np.array([1,2,3]*3) # Δημιουργία πίνακα με επανάληψη της λίστας 3 φορές
print(x)
x = np.repeat([1,2,3],3) # Δημιουργία πίνακα με επανάληψη των στοιχείων της λίστας 3 φορές
print(x)
x = np.array(lin*3) # Πολλαπλασίάζει τις τιμές του array με τιν τιμή 3
print(x)

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]
[  0.    1.5   3.    4.5   6.    7.5   9.   10.5  12. ]


In [21]:
p = np.ones([2,3],int) # Δημιουργία πίνακα 2x3 με ακέραιες τιμές ίσον 1
print(p)
print('')
x=np.vstack([p,2*p]) # Δημιουργία πίνακα πρόσθετου σε γραμμές (vertical) στον προηγούμενο με τιμές του υπολογισμού
print(x)
print('')
x=np.hstack([p,2*p]) # Δημιουργία πίνακα πρόσθετου σε στήλες (horizontal) στον προηγούμενο με τιμές του υπολογισμού
print(x)

[[1 1 1]
 [1 1 1]]

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


## Πράξεις με Arrays

In [24]:
# Πράξεις μεταξύ Arrays
print(x)
print(y)
print(x+y) # Πρόσθεση στοιχείων αντίστοιχης θέσης
print(x*y) # Πολλαπλασιασμός στοιχείων αντίστοιχης θέσης
print(x**2) # Ύψωση στο τετράγωνο των στοιχείων
print(x.dot(y)) # Πρόσθεση όλων στοιχείων των arrays

[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]
[1 4 9]
32


In [26]:
z = np.array([y,y**2])
print(z.shape) # Επιστρέφει τις δοιαστάσεις του πίνακα
print(z.T) # Κάνει transpose τον πίνακα (τις γραμμές στήλες και το ανάποδο)
print(z.dtype) # Επιστρέφει τον τύπο του array
z = z.astype('f') # αλλαγή στον τύπο του πίνακα
print(z.dtype) # Επιστρέφει τον τύπο του array

(2, 3)
[[ 4 16]
 [ 5 25]
 [ 6 36]]
int32
float32


In [27]:
z = np.array([1,2,3,4,5])
print(z.sum()) # Sum value of array
print(z.min()) # Min value of array
print(z.max()) # Max value of array
print(z.mean()) # Mean/Average value of array
print(z.std()) # Standard deviation value of array
print(z.argmax()) # Maximum of Index of array
print(z.argmin()) # Minimum of Index of array

15
1
5
3.0
1.41421356237
4
0


In [31]:
s = np.arange(13)**2
print(s)
s[0], s[3], s[7:10]
s[4]
s[-4]
s[-4:]
print()

r = np.arange(36)
r.resize(6,6)
r[2,2]
r[3,3:6]
r[:2,:-1]
r[-1,::2] # Επιλογή στοιχείου κάθε δυο θέσεις (μια παρά μια)
r[r>30] # Τα στοιχεία που έχουν τιμή > 30
print(r)
print()

r[r>30] = 30
r2=r[:3,:3]
r2[:] = 0
print(r)
print()

copyArr = r.copy()
copyArr[:] = 10
print(copyArr)
print()
print(r)


[  0   1   4   9  16  25  36  49  64  81 100 121 144]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [33]:
test = np.random.randint(0,10,(4,3)) # Δημιουργία πίνακα διαστάσεων 4x3 με τυχαίους ακέραιους αριθμούς μεταξύ 0 και 10
print(test)
print()
for row in test:
    print(row)
print()
for i in range(len(test)):
    print(test[i])
print()    
for i,row in enumerate(test):
    print('row', i, 'is', row)     
print()    
test2 = test**2    
test2    
print()
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[[2 8 0]
 [4 1 0]
 [3 1 6]
 [4 5 3]]

[2 8 0]
[4 1 0]
[3 1 6]
[4 5 3]

[2 8 0]
[4 1 0]
[3 1 6]
[4 5 3]

row 0 is [2 8 0]
row 1 is [4 1 0]
row 2 is [3 1 6]
row 3 is [4 5 3]


[2 8 0] + [ 4 64  0] = [ 6 72  0]
[4 1 0] + [16  1  0] = [20  2  0]
[3 1 6] + [ 9  1 36] = [12  2 42]
[4 5 3] + [16 25  9] = [20 30 12]
